server:
  port: 80
spring:
  application:
    name: hystrix-openfeign-consumer

eureka:
  client:
    register-with-eureka: false
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/

#feign.hystrix.enable开启服务降级 这里idea虽然不提示 但是写上去之后是会有效果的。
#feign.circuitbreaker.enable 配置的是feign调用service的fallback
feign:
  hystrix:
    enabled: true
  circuitbreaker:
    #这个配置以前是通过在主启动类通过注解进行的@EnableCircuitbreaker 好像是
    enabled: true #这个的作用是打开断路器